awslabs/cdk-eks-blueprints

.github/workflows/ci.yaml, lib/addons/argocd/index.ts, lib/stacks/cluster-types.ts, lib/stacks/eks-blueprint-stack.ts, package.json
May need an issue (design bootstrap support)
Added postDeploy lifecycle hook optionally implemented by Cluster AddOns.
=> Added postdeploy lifecycle hook (for addons)

docs/addons/index.md, docs/addons/metrics-server.md
*Issue #, if available:* #105
Add documentation for metrics server add on and example of how it can be used for kubernetes dashboard.
=> add docs for metrics server addon

ci/buildspec.yml
When a pr is made from a fork, e2e tests currently fail as the commit id from the fork is not in the upstream tree.
=> fetch pr head before merge

lib/addons/nginx/index.ts, lib/utils/addon-utils.ts, test/stacks.test.ts
*Issue #, if available:* #197
Adding a new `@dependable([list of AddOns])` decorator to handle addon dependencies to remove the repeatable code for asserting an dependent addon is scheduled as well as create resource dependencies in the cloudformation resources.
=> refactor for decorator pattern for handling inter-addon dependencies

lib/stacks/eks-blueprint-stack.ts
Issue discovered with pipelines when using different certificates for each stage. 
Resource providers were overwriting each other after clone. 
=> fixed error with resource providers being overridden

docs/getting-started.md
argocd getting-started example using team-burnham namesapce to port-forward the guestbook-ui, the guestbook-ui svc is currently deployed under team-riker team.
Relevant PR - https://github.com/aws-samples/ssp-eks-workloads/pull/4
doc fix to use the right team and namespace 
=> docfix: use team-riker namespace argo dev example

lib/addons/cluster-autoscaler/index.ts
*Issue #, if available:* #253
According to the helm chart documentation ([here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#permissions) and [here](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler#aws---using-auto-discovery-of-tagged-instance-groups)), couple of things were added/fixed to ensure the addon deploys correctly. Namely:
- Adding `"ec2:DescribeInstanceTypes"` in the IAM Policy
- Revising the chart value from `autoDiscovery.cluster` to `autodiscovery.clusterName`
Including the above two configuration items addressed the issue upon testing.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Cluster Autoscaler hotfix

lib/addons/nginx/index.ts
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
* Changed the path of Helm Values to httpsPort.targetPort and httpPort.enabled, when a Certificate Name is set according to the Helm Chart.
=> addon-nginx-ingress: fixed path to httpsPort.targetPort and httpPort enabled

docs/addons/opa-gatekeeper.md
Refresh of OPA Gatekeeper documentation:
1. Added usage section for adding gatekeeper to your blueprint 
2. Added section for key terminology
3. Used simpler example (all namespaces must be created with labels)
4. Added additional links for exploration
=> Updating opa gatekeeper documentation

lib/addons/argocd/index.ts
Addresses  https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24348.
=> bump up argocd to address CVE-2022-24348

lib/addons/secrets-store/index.ts
The repo URL used is not a valid chart repository, causing the following error:
> Error: looks like "https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/main/charts" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/main/charts/index.yaml : 404 Not Found
I've updated the repo URL to the one given by the upstream projects documentation on installing via Helm:
https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#deployment-using-helm
=> Use correct helm repo for secret-store-csi-driver

docs/addons/kubevious.md
Added a section to Kubevious documentation indicating that Persistent volume must be deleted manually as per the Kubevious documentation
=> Added PV section to Kubevious Documentation

lib/addons/aws-loadbalancer-controller/index.ts
https://github.com/aws-quickstart/ssp-amazon-eks/issues/312
Deploying ALB controller to EKS Fargate requires passing the VPC ID. It is better to pass VPC ID to the ALB controller chart, regardless it is EC2 or Fargate EKS, because EKS security best practice recommends to block the EC2 metadata service from EC2 nodes as well.
=> fix: pass VPC ID for ALB controller

ci/buildspec.yml
Otherwise CDK 2 builds fail
Related to CDK v2.0 and renaming
Updated nodejs version in the CI spec to enable e2e tests for the PR
=> Update buildspec to use node v16

.npmignore, lib/cluster-providers/types.ts, package.json
*Description of changes:* amiType for managed node group was incorrectly set and did not allow other supported AMI types.
=> bug fix for ami type

docs/addons/index.md, mkdocs.yml
This PR will add the Dynatrace OneAgent Operator to the Docs (@shapirov103) and fixed the Link for the keptn AddOn after renaming the module.
=> Add Dynatrace to the Docs and fixed keptn GitHub Repo link

lib/utils/object-utils.ts, package.json
*Description of changes:* fixed to leverage lodash. Discovered that on large blueprints fully recursive call fails with stack overflow. 
=> clone deep refactored back to lodash to prevent recursion stack overflow

lib/utils/yaml-utils.ts, package.json
*Issue #, if available:* #333 
Fix for team manifest dir issue. Async read of dir and files resulted in synthesis finishing before the manifests got a chance to be added. (#333 )
=> fixing issue for team manifest dir

docs/core-concepts.md
Ec2ClusterProvider is referenced but it should be MngClusterProvider
=> docs: correct default cluster provider

mkdocs.yml
Pixie is listed as an available AddOn in the [Overview](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/), but is missing in the expanded AddOns navigation menu.
Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>
=> Add Pixie to docs nav

lib/pipelines/code-pipeline.ts
…MS key for artifact bucket
*Issue #384
*Description of changes:
Added method to set crossAccountKeys to true. This method sets [aws-cdk-lib » pipelines » CodePipeline](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#crossaccountkeys) constructor property crossAccountKeys to true. otherwise it is false if not called.
=> bugfix: add crossAccountKeys boolean flag for Pipelines

lib/addons/external-dns/index.ts, lib/spi/types.ts, package.json
*Issue #, if available:* coming
*Description of changes:* increased version of the External DNS helm chart
minor debugging improvements
validated manually as e2e tests currently don't have a hosted zone to test with.
Automated testing of external DNS is covered in [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/examples/blueprint-construct/index.ts) issue.
=> External DNS fixed, upgraded version for deployment

docs/addons/aws-for-fluent-bit.md
Unfortunately the key of region is `awsRegion` instead of `region` like others
Check https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml#L119
=> Correct key-value of elasticSearch

lib/addons/core-addon/index.ts, lib/addons/coredns/index.ts, lib/addons/ebs-csi-driver/index.ts, lib/addons/kube-proxy/index.ts, lib/addons/vpc-cni/index.ts
*Issue #, if available:* #419 
*Description of changes: 
1. Standardization of the `core-addon` module to allow service account name as additional parameter and using the same to create service account for the addon using this model. 
2. Added a dependency to `CfnAddon` to avoid race condition while deployment of the addons.
3. Fixing Issue Related to EBS CSI Driver - deployed with incorrect trust relationship in `ebs-csi-driver` Addon.
4. Adding SA Name to pass as parameter to `CoreAddon` on `coredns`, `kube-proxy` and `vpc-cni` Addons.
Also 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice
=> Fixing EBS CSI Driver Addon and coreAddon Modules

docs/addons/karpenter.md, lib/addons/karpenter/index.ts, package.json
#465 
- Updated doc to notify users for possible issues using Fargate with Karpenter version prior to 0.14.0 and the fix.
- Upgrade default Karpenter to 0.14.0
- Prepare for Blueprints 1.2.0 release.
=> karpenter fix, upgrade and prep for 1.2.0 release

docs/addons/kubecost.md
when importing kubecost it's suppose to be : 
import { KubecostAddOn } from '@kubecost/kubecost-eks-blueprints-addon';
NOT import { KubecostAddOn } from '@kubecost/kubecost-blueprints-addon'; because the package that was installed was @kubecost/kubecost-eks-blueprints-addon
=> Update kubecost.md to the correct import

lib/addons/istio-base/index.ts
The istio-system namespace resource was omitted from CF dependency graph. That is why deleting the stack caused trouble as the namespace was deleted before other resources placed there. 
=> Fixed the istio-system namespace missing from dependency graph

lib/addons/karpenter/index.ts, test/karpenter.test.ts, test/stacks.test.ts
#494 
PR addresses:
- Currently, the Karpenter Add-on does not export Instance Profile in any way. This is necessary for users to add as part of provisioners. This PR will expose the name of the Instance Profile as a CloudFormation output.
- Separate Karpenter Addon suite of unit tests
- Consolidation check fixed.
=> Add Karpenter Node Instance Profile Name as a Cfn Output

lib/addons/ebs-csi-driver/index.ts
*Issue #, if available:* n/a
Changing the `saName` broke the EBS CSI Driver add-on, this PR reverts that change. The service account name used by the addon is still `ebs-csi-controller-sa`.
=> Revert saName for EBS CSI Driver

lib/addons/karpenter/index.ts
*Issue #, if available:* n/a
When interruption handling is enabled for Karpenter, the SQS queue is created with `queueName` set to `stackName`, but the value passed to the helm chart has `interruptionQueueName` set to `cluster.clusterName`. This results in Karpenter complaining about being unable to find the SQS queue:
```
ERROR    controller.interruption    getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: T
he specified queue does not exist for this wsdl version.
```
This change sets `interruptionQueueName` to `stackName`.
=> Fixed karpenter interruptionQueueName

docs/teams/teams.md
When specifying a `userRoleArn` in a Team, the path should be stripped. I added a note and a link to the documentation.
=> Add note about userRoleArn in teams.md

lib/addons/external-dns/index.ts
rationale: needed to work with having both a internal and external loadbalancer: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/public-private-route53.md
Uses the chart name to create service account and as the id for the deployment on CDK
=> Allow multiple ExternalDNS addons

lib/resource-providers/hosted-zone.ts
*Issue #, if available:* n/a
It is not currently possible to have multiple instances of DelegatingHostedZoneProvider, as the id for `delegationRole` is set to a static string. This causes the following error:
> Error: There is already a Construct with name 'MutableRoleDelegationRole' in EksBlueprint
=> fix: allow multiple DelegatingHostedZoneProvider instances

docs/addons/jupyterhub.md, lib/addons/jupyterhub/index.ts
Currently to leverage ACM certificate for JupyterHub Ingress, user must manually annotate once the certificate is created (or read in using Lookup). This PR will ensure the addon will automatically apply the annotation using user provided certificate.
Adds a configuration for user to be able to provide the name of an ACM certificate for annotation. 
=> Certificate addition for JupyterHub addon

lib/addons/karpenter/index.ts
*Issue #, if available:* #587
*Description of changes:* If deploy more than 2 EKS clusters are deployed in a Stack with Karpenter addons, an "Export with name KarpenterInstanceProfileName is already exported by stack {cdk-eks-blueprints-id}" error occurs.
Minor revision to add random names appended to those role names.
=> Addressing multiple EKS role name/instance name issue

README.md, docs/README.md, docs/getting-started.md, examples/blueprint-construct/index.ts, package.json
*Issue #, if available:* None
*Description of changes:* CDK updates for v2.54 addressed build issue due to mismatching typescript version (See [issue](https://github.com/aws/aws-cdk/issues/23126), [changelog under bug fix](https://github.com/aws/aws-cdk/releases/tag/v2.54.0)). Therefore, we no longer need to manually install typescript. CDK will include typescript with appropriate version automatically.
This PR will remove those commands in our documentations.
=> Manual typescript update removed from doc due to CDK update

examples/blueprint-construct/index.ts, lib/addons/karpenter/index.ts
[karpenter] add support for `Provisioner` limits
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>
=> [karpenter] add support for `Provisioner` limits

docs/addons/jupyterhub.md, lib/addons/jupyterhub/index.ts
*Description of changes:* If the Ingress option is disabled, the proxy svc will use `ClusterIP` and not `LoadBalancer`, and therefore removing the option to expose using NLB. This will require users to expose the svc using port-forwarding to access via `localhost`.
=> Feature/Jupyterhub: Removed option to expose proxy svc using NLB

examples/blueprint-construct/index.ts, lib/addons/aws-for-fluent-bit/index.ts
*Issue #, if available:* #619
- Added Helm Chart dependency on serviceaccount
- Removed namespace creation (default to `kube-system` which already exists)
=> AwsForFluentBitAddOn: Bug Fix on Helm Chart dependency

lib/addons/jupyterhub/index.ts, test/jupyterhub.test.ts
*Issue #, if available:* #616
*Description of changes:* We are removing AWS Load Balancer Controller Add On dependency when the JupyterHub proxy service is using ClusterIP type (and therefore does not require NLB or ALB).
=> JupyterHubAddOn: Removing AWS Load Balancer Controller dependency issue for ClusterIP service

lib/addons/vpc-cni/index.ts
*Issue #, if available:* **N/A**
All environment variable names and values must be strings in k8s pods (including the aws-node daemonset pods). See [EnvVar docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#envvar-v1-core).
Numeric values are required for the `warmPrefixTarget` property and others. However passing the value verbatim as a number causes an error:
```
ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.env.WARM_PREFIX_TARGET: integer found, string expected, $.env.WARM_ENI_TARGET: integer found, string expected]
```
**Disclaimer:**
- I am sure about the (non)string type issue
- I have manually  tested the type-casting expression to be correct for strings, booleans and numbers …
=> Convert all vpc-cni environment variables to string

lib/resource-providers/kms-key.ts
the KMS key resource provider
*Issue #, if available:* #644
Adding KMS keyId as an optional input parameter for the KMS provider. Users can provide the KMS key alias and keyId to use the existing key.
=> Adding backwards compatibility with v1.6.0 for KMS resource provider

README.md, docs/README.md, docs/getting-started.md, lib/pipelines/code-pipeline.ts
With 1.7.0 release, CDK version should be documented as 2.76.0 (as was updated in `package.json`). This will revise to reflect changes in all documentations.
=> CDK version change to 2.76.0 from 2.72.0 per 1.7.0 release

lib/addons/efs-csi-driver/iam-policy.ts
Adding the missing IAM permissions for the EFS CSI driver `elasticfilesystem:TagResource`
=> Adding the missing IAM permissions for the EFS CSI driver

lib/cluster-providers/generic-cluster-provider.ts, lib/cluster-providers/types.ts, test/resource-providers/resource-proxy.test.ts
*Issue #, if available:* https://github.com/aws-quickstart/cdk-eks-blueprints/issues/643
Add requireImdsv2 to ManagedNodeGroup's LaunchTemplateProps so that clusters using managed node groups will create ec2 instances with imdsv1 disabled.
=> Add requireImdsv2 to ManagedNodeGroup's LaunchTemplateProps

examples/blueprint-construct/index.ts, lib/cluster-providers/generic-cluster-provider.ts, package.json
*Description of changes:* release prep for 1.7.1
=> setting default kubectllayer to 1.25, requiredIdmsv2 e2e test, patch 

lib/addons/jupyterhub/index.ts, package.json
*Description of changes:* This fixes the syntax error on the Load Balancer addon check for JupyterHub addon. This PR also updates release version to 1.7.2 for quick patch, as issues exist with patterns repo.
=> Quick fix on wrong syntax for ALB addon check

lib/addons/nginx/index.ts, package.json
*Issue #, if available:* #672
Added proper types and validation including HTTPS to HTTP port redirection when terminating at the NLB level.
=> nginx addon fails on schema validation when certificate is specified. 

lib/addons/cluster-autoscaler/index.ts
=> Fix issue #709

docs/addons/cluster-autoscaler.md, docs/addons/grafana-operator.md, docs/getting-started.md, docs/resource-providers/index.md
*Issue #, if available:* #632
Added documentation to explain creating VPC Resource Providers and added links to other resource providers
=> docs: add clarity for creating own VPC resource provider

lib/addons/apache-airflow/index.ts
*Description of changes:* Dependency for EFS Kubernetes resources (storageclass and PVC) added so that they are provisioned after namespace creation.
=> [Apache Airflow addon] Dependency added for EFS

docs/addons/external-secrets.md, examples/blueprint-construct/index.ts, lib/addons/external-secrets/index.ts
=> Upgrading support for SSM for External Secrets

lib/addons/aws-loadbalancer-controller/iam-policy.ts
*Issue #, if available:* #737
Added missing permission based on the latest AWS Load Balancer Controller IAM policy reference: https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.2/docs/install/iam_policy.json
Also refer to this comment: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692#issuecomment-1426195505
=> Update AWS Load Balancer Controller Addon IAM Policy to fix permission issue during ALB ingress creation

docs/addons/fluxcd.md, docs/addons/vpc-cni.md, docs/cluster-providers/generic-cluster-provider.md, examples/blueprint-construct/index.ts, lib/addons/fluxcd/gitrepository.ts, lib/addons/fluxcd/index.ts, lib/addons/grafana-operator/index.ts, lib/addons/vpc-cni/index.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/cluster-providers/types.ts
This PR takes care of Upgrading Grafana Operator, Adding SecretRef to Flux and Upgrading VPC CNI.
=> Windows Node Group Support, Upgrade Grafana Operator, Add SecretRef to Flux and Upgrade VPC CNI.

docs/addons/karpenter.md, examples/blueprint-construct/index.ts, lib/addons/karpenter/index.ts, lib/spi/types.ts
*Issue #, if available:* #726
- Adding AMI Selector for the Provisioner
- Using NodeTemplate in addition to the provisioner (needed to acommodate AMI Selector)
=> Karpenter Addon: adding AMI Selector, refactor to use NodeTemplate

lib/addons/argocd/index.ts
Argo CD helm version is outdated.
Helm chart version 5 introduced couple of changes, and I think we should upgrade it. It was tested on the pipeline-multi-env-gitops pattern
=> Bump ArgoCD default version to 5.37.0 (currently latest)

examples/blueprint-construct/index.ts, lib/cluster-providers/generic-cluster-provider.ts
=> Fixing Launch Template Issue #768

docs/addons/metrics-server.md, lib/addons/kube-state-metrics/index.ts, lib/addons/metrics-server/index.ts
#772 
Add `createNamespace` support for Metrics Server addon
Tests run successfully 
```
Test Suites: 13 passed, 13 total
Tests:       59 passed, 59 total
Snapshots:   0 total
Time:        22.749 s
Ran all test suites.
```
=> Adding create Namespace support for Metrics-Server addon

lib/stacks/eks-blueprint-stack.ts
Fix #778.
Add `cloneEnv` method.
See description of 778 --> 
AWS CDK has a basic type of cdk.Environment, which is an object holds the account and the region for a target environemtn for deployment.
Having a new clone function that accept a cdk.Evironment type can simplify code using the clone method
=> new withEnv function

docs/addons/karpenter.md, examples/blueprint-construct/index.ts, lib/addons/karpenter/index.ts
Adding tags option to the default provisioner so that Karpenter adds tags to all resources created, including EC2 Instances, EBS volumes and Launch Templates.
This change supports accounts with governance requirements where tags are required such as enforcing use of the [AWS Instance Scheduler](https://aws.amazon.com/solutions/implementations/instance-scheduler-on-aws/)
Karpenter allows overrides of the default "Name" tag but does not allow overrides to restricted domains (such as "karpenter.sh", "karpenter.k8s.aws", and "kubernetes.io/cluster"). This ensures that Karpenter is able to correctly auto-discover machines that it owns, so Karpenter will validate these requirements itself.
An integration test would verify that the tags are …
=> feat: adding tag option for karpenter's default AWSNodeTemplate

lib/addons/karpenter/index.ts, test/karpenter.test.ts
_Issue #, if available:_
Closes #802
_Description of changes:_
- Added initially failing unit test demonstrating the issue.
- Made test green by merging user provided values with the addon provided values.
=> fix(addons/karpenter): merge user provided `settings.aws` values with addon provided values.

docs/cluster-providers/fargate-cluster-provider.md, lib/cluster-providers/fargate-cluster-provider.ts
Use a TypeScript-native mapping type for Fargate profiles instead of the non-idiomatic `Map<>` type. The old type remains supported for backward compatibility, but should be deprecated.
=> Use TypeScript mapping for Fargate profile

docs/builders/index.md, docs/builders/observability-builder.md, lib/builders/observability-builder.ts, mkdocs.yml
=> Observability Builder for Observability Accelerator

lib/addons/karpenter/index.ts, test/karpenter.test.ts
*Issue #, if available:* #799
*Description of changes:* Interruption Queue Name was resolved to the stack name even though the queue was disabled. This PR will fix to ensure if the queue is disabled, then the helm interruption queue name will resolve to a blank value (as intended for default helm value).
=> fix(addon/karpenter): Disable Interruption Queue on Helm when the addon flag is false. 

bin/main.ts, docs/addons/fluxcd.md, lib/addons/fluxcd/gitrepository.ts, lib/addons/fluxcd/index.ts, lib/addons/fluxcd/kustomization.ts
Added a new fluxcd repository object, and array of those objects to fluxcd props to allow for multiple repositories and multiple paths.
Changes are breaking changes
=> Fluxcd fixes

lib/addons/external-dns/index.ts, package.json
*Issue #791*
Unlike the `bitnami/external-dns chart`, `kubernetes-sigs/external-dns` did not support the previously used helm value to set zoneIdFilters. I.e. external dns tried to access all hosted zones in the AWS account. This led to a crash because the policies in the `HelmAddOn` just allow access to the specified hosted zones.
*Options to fix this:*
1: Use the `domainFilters` in the `kubernetes-sigs/external-dns` and pass in the correct domains. 
Problems with this approach are that hosted zone ids have to be passed anyways to configure the correct policy. 
2: Just set the appropriate command line flag `--zone-id-filter` for each hosted zone id. The flags can be set by the helm value `extraArgs`.
*How did I test it:*
I built the node module. Then I copied …
=> Add zone id filter using external args.

.github/workflows/docbuild.yml, lib/builders/index.ts, lib/builders/observability-builder.ts, lib/builders/windows-builder.ts, lib/index.ts, package.json
=> Fixing GH Actions

docs/extensibility.md
*Description of changes:*  Extensibility code snippets for helm and non-helm add-ons were incorrect as they did not import blueprints as a library causing confusion from some customers. 
=> fixed code snippets to create helm and non-helm addons

lib/builders/gpu-builder.ts
*Description of changes:* Concatenate instanceClass and instanceSize for instanceType prop
=> Gpu Builder Instance Type prop fix

lib/addons/karpenter/index.ts, test/karpenter.test.ts
*Description of changes:* Added new values for Windows support of Karpenter : Windows 2019 and Windows2022 with relevant tests.
=> Added support for Windows2019 and Windows2022 as amifamily

lib/addons/karpenter/index.ts, test/karpenter.test.ts
Reverts aws-quickstart/cdk-eks-blueprints#836
=> Revert "Added support for Windows2019 and Windows2022 as amifamily"

lib/addons/karpenter/index.ts
*Description of changes:* Added Windows2019 and Windows2022 as accepted values for amiFamily
=> Added Windows2019 and Windows2022 to amiFamily for Karpenter

lib/cluster-providers/generic-cluster-provider.ts, lib/stacks/eks-blueprint-stack.ts, test/clusterprovider.test.ts
*Issue #, if available:*  #841 
=> #841 fixing version issue

docs/pipelines.md, lib/pipelines/code-pipeline.ts
*Issue #, if available:* #633  (potentially)
Added support for path specification with code pipeline.  See docs for usage.
Customers can define their blueprints IaC code under arbitrary path in the repo. 
=> added path support to code pipeline:

docs/addons/vpc-cni.md, lib/addons/vpc-cni/index.ts
*Issue #850 :*
Introduce enableNetworkPolicy parameter and when is set to 'true' enable Network policy with AWS VPC-CNI plugin.
For example:
```typescript
const addOns: Array<blueprints.ClusterAddOn> = [
new blueprints.addons.CoreDnsAddOn(),
new blueprints.addons.KubeProxyAddOn(),
new blueprints.addons.EbsCsiDriverAddOn(),
new blueprints.addons.VpcCniAddOn({ enableNetworkPolicy: 'true', version: 'v1.15.0-eksbuild.2' })
];
```
=> VpcCniAddOn - enable supports of Kubernetes Network Policies with enableNetworkPolicy after Amazon VPC CNI version 1.14.0 #850

docs/builders/observability-builder.md, lib/builders/observability-builder.ts
*Issue #, if available:* https://github.com/aws-observability/cdk-aws-observability-accelerator/issues/118 
*Description of changes:* Documentation stating that in-place upgrades for new and existing clusters should be possible with control plane logging.
=> Updating documentation about in-place upgrades

docs/addons/adot-addon.md, docs/addons/amp-addon.md, docs/addons/xray-adot-addon.md, examples/blueprint-construct/index.ts, lib/addons/adot/index.ts
*Issue #:* #869
Adds support for non-default namespace for ADOT deployment.
*Tests:*
```
make run-test
Test Suites: 14 passed, 14 total
Tests:       67 passed, 67 total
Snapshots:   0 total
Time:        21.321 s
#Post Deployment validations:
└> k get all -n adot                                                                                                                                                 [9/11/23| 5:54PM]
NAME                                                READY   STATUS    RESTARTS   AGE
pod/otel-collector-amp-collector-6b8996bf5d-lxv6w   1/1     Running   0          101m
pod/otel-collector-xray-collector-c76d86886-rhvjm   1/1     Running   0          101m
NAME                                               TYPE        CLUSTER-IP       EXTERNAL-IP …
```
=> fix: 869, support for non default namespace for adot

docs/addons/amp-addon.md
#876 
The constructor for the `CreateAmpProvider` class is shown below.
https://github.com/aws-quickstart/cdk-eks-blueprints/blob/a63f2721a7838ed1bc5e50b60a24d4b05375d8db/lib/resource-providers/amp.ts#L17
`workspaceTags` is an array type.
=> Docs: Fixed amp-addon.md typo

lib/addons/kubevious/index.ts
From [kubevious helm Doc](https://github.com/kubevious/helm/blob/master/README.md?plain=1#L172), current setpath of UI service type `kubevious.service.type` is not correct
Test:
- AddOn
```
AddOns.push(new KubeviousAddOn({
version: '1.2.1',
kubeviousServiceType: 'NodePort',
}));
```
- Deploy
```
➜  ~ k get svc -n kubevious
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubevious-backend-clusterip     ClusterIP   172.20.230.157   <none>        4000/TCP       28h
kubevious-collector-clusterip   ClusterIP   172.20.22.28     <none>        4000/TCP       28h
kubevious-guard-clusterip       ClusterIP   172.20.181.25    <none>        4000/TCP       28h
kubevious-mysql                 ClusterIP …
```
=> [kubevious AddOn] Correct kubevious service type setpath

docs/addons/karpenter.md, lib/addons/karpenter/index.ts, test/karpenter.test.ts
Adding in support to pass blockDeviceMappings through to karpenter as per https://karpenter.sh/v0.30/concepts/node-templates/#specblockdevicemappings
=> feat: adding support for karpenter blockdevicemapping

lib/addons/vpc-cni/eniConfig.ytpl, lib/addons/vpc-cni/index.ts
*Issue #, if available:* The current implementation of eniconfig manifest creation by default sets the eks cluster's security group id as secondary eni id. If a user wants to use an already existing security group id then its not possible now
Provides capability to specify an existing security group for EniConfig generated by vpc cni addon. The security group id is optional in CustomNetworkingConfig, if security group is not specified cluster security group id will be used.
This change is in reference to the Custom Networking documentation steps which specifies "Replace $cluster_security_group_id with the ID of an existing [security group](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html) that you want to use for each ENIConfig." …
=> Provision add custom security group to secondary eni in vpc cni addon custom networking

examples/blueprint-construct/index.ts, lib/addons/adot/index.ts, lib/addons/cloud-watch-insights/index.ts, lib/addons/core-addon/index.ts, lib/addons/coredns/index.ts, lib/addons/ebs-csi-driver/index.ts, lib/addons/eks-pod-identity-agent/index.ts, lib/addons/kube-proxy/index.ts, lib/addons/vpc-cni/index.ts, lib/builders/observability-builder.ts, test/amp.test.ts, test/coredns.test.ts, test/emr-eks.test.ts, test/kubeproxy.test.ts
Upgrade Core Addons to support MAP of Versions for Kubernetes versions
=> Upgrade Core Addons to support Default Versions from AWS sdk for different Kubernetes versions 

lib/addons/amp/collector-config-amp.ytpl
This PR updates the clusterRole that Amp AddOn creates to support ADOT container logs collection. Without these updates logs collection will not work for all namespaces and pods. These updates are based on container logs collection working example found at https://github.com/lewinkedrs/cop-401-instrumentation/blob/f970e59a55ef042a885423f6201602bd91ee5336/python-manual-instrumentation-sample-app/prometheus-daemonset.yaml#L181
=> feat: Amp AddOn - Update OTEL collector cluster role to support container logs collection

examples/blueprint-construct/index.ts, lib/addons/karpenter/index.ts, test/karpenter.test.ts
*Issue #, if available:* #899 #914
Volume Size on Blocked Device Mapping was mistyped. This PR addresses it, with the right test implementation under `examples`.
=> (karpenter add-on) Blocked Device Mapping EBS Volume Size type issue fix

docs/addons/ack-addon.md, lib/addons/ack/index.ts, lib/addons/ack/serviceMappings.ts
The EKS ack controller doesn't have a recommended managed policy, only an inline one, and the currently provided managed policy in blueprints doesn't seem to give any eks permissions, nor does any other managed policy seem to be appropriate. The best option is to support inline policies. There may be other ack controllers with similar issues, but EKS is the one I'm aware of.
Also, this file appeared to have CRLF, so I've converted it to LF to match the rest of the project - I suggest viewing the diff without whitespace
=> Ack addon must support inline policies for EKS

examples/blueprint-construct/index.ts, lib/addons/ssm-agent/index.ts
*Issue #, if available:* NA
*Description of changes:* The old version of SSM agent addon will be soon out of SLA due to https://alas.aws.amazon.com/AL2/ALAS-2024-2458.html
This update makes sure that latest version of SSM agent is install. This is a temporary fix and we need a permanent fix or the ability to pass this as a prop.
=> Update SSM agent version to 3.2.2222.0

lib/builders/windows-builder.ts
*Description of changes:* Change to use eks.nodeGroupOptions so we can have all options override in case it's needed.
=> Change to use eks.nodeGroupOptions in the builder

docs/addons/vpc-cni.md, lib/addons/vpc-cni/index.ts
Added and exposed the configuration for "enableWindowsIpam" for the vpc-cni add on. This will allow to turn on the configuration value for Windows EKS clusters while using the Windows patterns.
=> Added configuration value enableWindowsIpam for Vpc-cni add on

docs/addons/secrets-store.md, lib/addons/secrets-store/csi-driver-provider-aws-secrets.ts, test/secretproviderclass.test.ts
Closes #939 
Adds support for the `objectAlias` parameter via the `secretAlias?` input. This input lives next to `secretName` and allows for the name of the kubernetes secret to differ from the name of the AWS Secret or SSM Parameter it is sourced from.
=> feat(SecretProviderClass): add support for objectAlias

examples/blueprint-construct/index.ts, lib/addons/adot/index.ts, lib/builders/windows-builder.ts
```
kubectl get all -n adot
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/otel-collector-amp-collector-5db7c94fbd-kg2mp    1/1     Running   0          9m44s
pod/otel-collector-xray-collector-858f4c5454-5r8qk   1/1     Running   0          9m45s
NAME                                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/otel-collector-amp-collector-monitoring    ClusterIP   172.20.135.254   <none>        8888/TCP            9m44s
service/otel-collector-xray-collector              ClusterIP   172.20.159.154   <none>        4317/TCP,4318/TCP   9m45s
service/otel-collector-xray-collector-headless     ClusterIP   None             <none> …
```
=> Fix ADOT Versions

mkdocs.yml
Resolves an issue with the mkdocs config that was causing the Bedrock Team page to render incorrectly
=> chore(docs): use correct path to bedrock-team.md

lib/addons/karpenter/index.ts, test/karpenter.test.ts
*Issue #, if available:* #976
*Description of changes:* This is a test that reproduce the problem I faced in #976, I'll look at possible solution next. It's currently failing (hence the bug). Let me know if you think that is wrong.
=> [addons/karpenter] Covers the use of KubernetesVersion.of('1.28') syntax to get a KubernetesVersion

lib/addons/karpenter/index.ts
I've stumbled across a bug while installing karpenter: I can set the namespace in the KarpenterAddOnProps, but the createNamespace() and createServiceAccount() functions would still use the default variable as their namespace.
=> [Karpenter] Fix ignored namespace prop

lib/addons/aws-loadbalancer-controller/index.ts, lib/addons/ebs-csi-driver/index.ts
This PR resolve:
- issue #968 - allow to extend LB controller with helm values.
- issue #995 - allow ebs-csi-controller to have custom configurationValues.
These change have been tested on my current deployment.
=> Fix: allow to extend configurations of AWS LB controller and EBS CSI driver.

lib/addons/amp/collector-config-amp-daemonset.ytpl
*Issue #, if available:* 990
*Description of changes:* This PR adds the required cluster role for the daemonset template.
=> bugfix: Adds cluster role for otel daemonset deployment mode

lib/addons/external-dns/index.ts
Issue #1010 
The current default values will allow ExternalDNS to listen for Service and Ingress only.  If you're using something else, such as Istio or Envoy Gateway, it will not look for host names in Gateway, VirtualService, or HTTPRoutes.  This allows that override via helm values.
=> [feat] Add service override parameter to ExternalDNS props

README.md, docs/README.md, docs/getting-started.md, docs/internal/ci.md, lib/cluster-providers/generic-cluster-provider.ts, lib/pipelines/code-pipeline.ts, package.json, test/clusterprovider.test.ts, test/stacks.test.ts
*Issue #, if available:* Fixes [#1021](https://github.com/aws-quickstart/cdk-eks-blueprints/issues/1021)
*Description of changes:* 
Added tests for 1.30
cdk version update to 2.145.0
cleaned up old versions from 1.25 to 1.30
=> feat(generic-cluster-provider):  support kubectl lambda layer v1.30

.devcontainer/devcontainer.json, .devcontainer/postCreateCommand.sh, README.md
Introducing  Dev Containers Feature.
=> Feature to introduce Dev Containers

docs/addons/fluxcd.md, lib/addons/fluxcd/bucket.ts, lib/addons/fluxcd/index.ts, lib/addons/fluxcd/kustomization.ts
- implement support for FluxCD Bucket source: https://fluxcd.io/flux/components/source/buckets/
- bump FluxCD default version to 2.13.0
- use the more reliable OCI registry for the FluxCD Helm chart
- make indentation consistent within the modified files
- changed typo in `defaultKustomiationProps`
- basic use case tested
- kustomizations not tested
Example use:
```
.addOns(new blueprints.addons.FluxCDAddOn({
buckets: [
{
name: "bootstrap-bucket",
bucketName:base.bucket.bucketName,
bucketRegion: cdk.Aws.REGION,
}
],
}),
``` 
=> Add FluxCD support for S3 Bucket sources

lib/addons/karpenter/index.ts
Karpenter fails to shut down its nodes properly during cluster deletion due to a permission error caused by the premature deletion of the service account:
```
panic: failed to setup manager: failed to determine if *v1.Lease is namespaced: failed to get restmapping: failed to get server groups: the server has asked for the client to provide credentials
goroutine 1 [running]:
github.com/samber/lo.must({0x26921c0, 0xc0009765a0}, {0xc000b17a18, 0x1, 0x1})
github.com/samber/lo@v1.39.0/errors.go:51 +0x1bb
github.com/samber/lo.Must[...](...)
github.com/samber/lo@v1.39.0/errors.go:65
sigs.k8s.io/karpenter/pkg/operator.NewOperator()
sigs.k8s.io/karpenter@v0.36.0/pkg/operator/operator.go:183 +0x1418
main.main()
github.com/aws/karpenter-provider-aws/cmd/controller/main.go:33 +0x25
```
Updated the …
=> [Karpenter] Make sure to preserve the SA during chart deletion

lib/addons/cloud-watch-insights/index.ts, test/cloudwatch-insights.test.ts
*Issue #, if available:* #971, #948
=> Migrated CloudWatch Insights to new CoreAddons model

lib/resource-providers/hosted-zone.ts, lib/resource-providers/iam.ts, lib/spi/types.ts, lib/stacks/eks-blueprint-construct.ts, lib/stacks/eks-blueprint-stack.ts, lib/stacks/index.ts, test/resource-providers/efs.test.ts, test/resource-providers/s3.test.ts
Description of changes: Currently, EKS blueprint can be used by only cdk.stack users or the users who relies on stack derivates. All other users cannot use this package. So, this Generic construct will help the users of any kind to use eks blueprint code. 
Example: 
In our company, we use different stack named PipelineStack which is not able to use cdk.stack to deploy the resources created by the blueprint. Which resulted in writing our own blueprint/blueprint builder code. The current change will help to use the eks blueprint code directly.
=> Generic Construct for EKS blueprint

lib/addons/keda/index.ts
*Issue:*
Since v2.14.0, [#625](https://github.com/kedacore/charts/pull/625/files#diff-3b4e4c10436059483f20fa5b4b2e507a0bcead63f71af2c02ca41dbff3c8b3ad) updates some Helm chart values that are not backward compatible with the old settings. The serviceAccount has been separated per service, such as operator, metricServer, and webhooks.This causes the upgrade to v2.14.0+ to recreate the new operator serviceAccount without the IAM role annotation
- Update version to current latest v2.14.2
- Move creating namespace out of `irsaRole` condition check to avoid CDK delete `keda` namespace if we change irsaRole[] to empty
- Remove workaround for SQS Scalar https://github.com/kedacore/keda/issues/837 as KEDA-is-secure-by-default
- Update  `serviceAccount` to …
=> [KEDA] Update helm values to work from v2.14.0

docs/addons/karpenter.md, lib/addons/karpenter/index.ts, lib/utils/index.ts, lib/utils/pod-identity-utils.ts
*Issue:*
**Pod Identity Supports Notice**
Karpenter now supports using [Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) to authenticate AWS SDK to make API requests to AWS services using AWS Identity and Access Management (IAM) permissions.
- Introduce option to enable Pod Identity, this replaces IRSA method to manage credentials for Karpenter controller.
- Resources created for using Pod Identity
- IAM role with service principle `pods.eks.amazonaws.com` and allow actions `sts:AssumeRole` and `sts:TagSession`
- Pod Identity associations
- Service account created by Helm chart without `eks.amazonaws.com/role-arn` annotation
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> [Karpenter] Pod Identity Supports

lib/addons/ingress-nginx/index.ts
*Issue #, if available:* None
A small fix to update the `@default` value in the ingressClassName (for the new ingress-nginx addon) so it properly reflects the actual default.
I just ran into this when deploying the add-on and my helm charts are all wrong :-).
=> (Docs) ingress-nginx: Fix incorrect ingressClassName default comment

docs/addons/efs-csi-driver.md
1052
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/1052
Add notes around where to find EFS driver workshop to successfully deploy EFS driver with EKS blueprint
=> Add EFS driver notes

docs/addons/cluster-autoscaler.md
The rendering of the helm values in the website is messed up.
Added a newline which I think should fix the rendering.
=> docs: Fix rendering of helm values for cluster-autoscaler

cdk.json, docs/cluster-providers/asg-cluster-provider.md, docs/cluster-providers/generic-cluster-provider.md, docs/cluster-providers/mng-cluster-provider.md, examples/monorepo/cdk.json, lib/cluster-providers/asg-cluster-provider.ts, lib/cluster-providers/constants.ts, lib/cluster-providers/fargate-cluster-provider.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/cluster-providers/mng-cluster-provider.ts
Add support for deploying Cluster resource in an isolated subnet. CDK EKS already supports deployment in an isolated subnet and this is describes in this example: https://github.com/aws-samples/aws-cdk-examples/tree/main/java/eks/private-cluster. This PR just adds an "isolatedCluster" flag, which adds Cluster props to based on the example.
Tested and deployed successfully.
Note that given the lack of internet access, addon's which require access to public repositories (like AwsLoadBalancerControllerAddOn) cannot be used.
=> flag for deploy to isolated subnet

.devcontainer/devcontainer.json, .github/workflows/linkcheck.json, README.md, bin/main.ts, docs/README.md, docs/addons/index.md, docs/getting-started.md, docs/internal/ci.md, lib/addons/cloud-watch-insights/index.ts, lib/addons/core-addon/index.ts, lib/pipelines/code-pipeline.ts, package.json, test/cloudwatch-insights.test.ts
*Description of changes:* In prep for the release fixing test and libs to merge the pull request that are currently in the queue.
=> Fixed tests, build issues, upgraded CDK and libs

docs/addons/opa-gatekeeper.md, docs/opa-gatekeeper.md
I was reading the documentation of [OPA Gatekeeper](https://aws-quickstart.github.io/cdk-eks-blueprints/opa-gatekeeper/) and in [Usage](https://aws-quickstart.github.io/cdk-eks-blueprints/opa-gatekeeper/#usage) part, I noticed that `kubectl` was `pod` are abbreviated(that is not wrong at all) and in the other part they were written as `kubectl` and `pod`.
=> docs: fix notation fluctuation on OPA Gatekeeper

lib/addons/vpc-cni/index.ts
This PR adds support to provide values for certain settings of the VpcCniAddOn that were introduced in amazon-vpc-cni-k8s [v1.16.0](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.16.0) in PR [additional settings to the helm chart](https://github.com/aws/amazon-vpc-cni-k8s/pull/2715)
- enable-windows-prefix-delegation
- warm-prefix-target
- warm-ip-target
- minimum-ip-target
- branch-eni-cooldown
I verified that this code change does not introduce any functional changes for the already existing vpc-cni settings by comparing the generated cloud formation output for different sets of parameters generated with and without this change and assure they are equal. For the newly introduced vpc-cni settings I tested that they are deployed to an eks ckuster as desired.
By submitting this …
=> Additional Settings to VpcCniAddOn

lib/addons/gpu-operator/index.ts
Fixes #1063
Follows the recommended changes in that ticket, which links to https://github.com/NVIDIA/gpu-operator/issues/538
Note that I haven't tested it as I haven't got the means to do so.  Let me know if theres anything further I should do!
=> Update helm chart location for gpu-operator addon

docs/addons/efs-csi-driver.md
=> docs: fix CreateEfsFileSystemProvider args

lib/resource-providers/ipv6-iam.ts, package.json
*Issue #, if available:* #1094
*Description of changes:* Updated internal import, prepared for patch release
=> Fixed #1094 ipv6 cluster failure on internal import

lib/addons/aws-loadbalancer-controller/iam-policy.ts
*Issue #1096*
Expands the IAM permissions of the `aws-load-balancer-controller` role to what is recommended by the addon:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
=> fix: aws-load-balancer-controller service account missing IAM permissions

lib/addons/kube-proxy/index.ts
*Issue:*
```
22:09:53 | UPDATE_FAILED        | AWS::EKS::Addon                       | kubeproxyaddOn
Resource handler returned message: "Addon version specified is not supported (Service: Eks, Status Code: 400, Request ID: 5011efa8-0c30-4b51-9838-9a16e11518bd)" (RequestToken: 3efef0f1-7248-45a3-4665-f
a656c3f88f9, HandlerErrorCode: InvalidRequest)
```
Correct version: `v1.31.0-eksbuild.5`
=> Correct Kube-proxy mapping version for EKS v1.31

lib/resource-providers/vpc.ts
A debug `console.log()` seems to have been left in place that causes LookedUpVpc objects to be logged out when using imported (non-default) VPC/Subnets. This change removes that.
=> Remove console.log when looking up non-default VPCs

lib/addons/amp/collector-config-amp-daemonset.ytpl, lib/addons/amp/collector-config-amp.ytpl, lib/addons/cloud-watch-insights/index.ts, lib/addons/cloudwatch-adot-addon/collector-config-cloudwatch.ytpl
Added new jobs to scrape kube-scheduler and kube-controller-manager metrics from EKS. This will be released on 11/18.
=> Added new scraping jobs for KSH and KCM metrics

docs/addons/s3-csi-driver.md, lib/addons/index.ts, lib/addons/s3-csi-driver/iam-policy.ts, lib/addons/s3-csi-driver/index.ts, mkdocs.yml
S3 CSI Driver 
This commit adds a new file `iam-policy.ts` that contains the IAM policy statements for the S3 CSI driver. It also adds a new file `index.ts` that implements the S3 CSI driver addon. The addon creates a service account, attaches the IAM policy to the service account's role, and deploys the addon to the cluster. The commit also includes some helper functions and default options for the addon.
=> Add S3 CSI Driver IAM policy as blueprints addon

lib/addons/aws-loadbalancer-controller/index.ts
N/A
`AlbController` webhook isn't ready directly after the AddOn deployment. 
This cause a race condition when another AddOn creates Kubernetes Manifest resources that rely on it, like `TargetGroupBinding`.
Sometimes it is successful, sometimes not. To avoid such situations, `addHelmChart` of `AlbController` should wait similar as it was implemented for `External Secrets`: https://github.com/aws-quickstart/cdk-eks-blueprints/pull/514
Example of such an error when the proposed fix is not applied:
```
Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (InternalError): error when creating "/tmp/manifest.yaml": Internal error occurred:
failed calling webhook …
```
=> fix(aws-lb-controller): wait till deployed

examples/blueprint-construct/index.ts, lib/addons/s3-csi-driver/iam-policy.ts, lib/addons/s3-csi-driver/index.ts
None
Tweak the new S3 CSI Addon so it supports multiple S3 buckets.  Looking at the CSI Driver itself, it does support multiple bucket; it's just the Service Account creation here which is currently constrained to a single bucket name.
One thing I'm not sure on is how this changes the Props object - it means consumers will have to change their usage.  I could instead make s3BucketNames a `string | string[]` to handle this, but I'm not sure if its worth the effort.  What are your thoughts?
=> S3 CSI Addon - Support multiple buckets

lib/addons/karpenter/index.ts
N/A
The instance profile created has a dependency on the instance role, but this is not captured by the level 1 construct `CfnInstanceProfile`. Explicitly adding the dependency so that the addon can be reliably destroyed in CloudFormation.
=> Adding dependency on instance role

examples/examples.ts, lib/cluster-providers/generic-cluster-provider.ts
Unable to create a cluster in the public subnets only
=> Private cluster defect (always on)

lib/addons/helm-addon/index.ts
Increasing cap for version which allows passing extra custom parameters in the version field that will be used for installation (valid for OCI repos).
=> Updating cap on version in helm addons

lib/addons/fluxcd/index.ts
*Issue #, if available:* #1125
This PR adds a wait duration for flux CD addon so that the helm install waits for CRDs
=> Fix for issue #1125

examples/examples.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/cluster-providers/types.ts, test/resource-providers/resource-proxy.test.ts
*Issue #, if available:* #1128
Add option `httpPutResponseHopLimit` to `nodeGroup.launchTemplate`
=> [cluster-provider] Add option httpPutResponseHopLimit to nodeGroup.launchTemplate

lib/addons/s3-csi-driver/iam-policy.ts, lib/addons/s3-csi-driver/index.ts
*Issue #, if available:* None
The IAM policy for the S3 CSI Driver is missing permissions for customer managed KMS keys (when used).  This PR adds support for specifying KMS Keys by ARN.  The new props property is optional as I suspect this isn't going be needed most of the time!
Note: the kms permissions detailed in the Policy are enough to get it all working for me; I struggled to find any documentation to confirm that this includes all permissions we may need.  
=> S3 CSI Driver - add support for Customer Managed KMS Keys

lib/addons/secrets-store/index.ts
The main branch of aws/secrets-store-csi-driver-provider-aws is a constant work in progress. The only authoritative things we release are:
- container images and their associated tags
- helm chart versions
- git version tags
We recommend you please pin the URL for the provider installation yaml instead of pointing to the tip of main. This recently broke a customer [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/457).
=> Pin aws/secrets-store-csi-driver-provider-aws YAML installer to a git version

mkdocs.yml
*Issue #, if available:* N/A
*Description of changes:* Removing the duplicate AddOns > Ingress Nginx navigation link in the docs site
=> docs: remove duplicate ingress-nginx nav link

lib/addons/karpenter/index.ts, lib/addons/karpenter/karpenter-v1.ts
This PR fixes a typo in the KarpenterV1AddOn that prevents Karpenter nodes from successfully joining the EKS cluster.
The addon was using `system:bootstrapper` (singular) instead of `system:bootstrappers` (plural) in the aws-auth ConfigMap configuration. This caused node registration failures with Karpenter-provisioned nodes unable to authenticate with the cluster.
- Changed `groups: ["system:bootstrapper", "system:nodes"]` to `groups: ["system:bootstrappers", "system:nodes"]` in `lib/addons/karpenter/karpenter-v1.ts`
- ✅ All existing tests pass
- ✅ `make build` completes successfully
- ✅ `make lint` passes
- ✅ Verified the fix in a production EKS cluster where nodes now successfully join
- [Kubernetes TLS bootstrapping documentation](https://kubernetes.io/docs/reference/access-authn-authz …
=> fix: correct typo in Karpenter aws-auth groups

lib/addons/adot/index.ts
N/A
Adds version mapping for ADOT in EKS 1.32 and 1.33 (both missing currently)
=> Add adot version mapping for EKS 1.32 and 1.33
