package-lock.json, package.json
Bumping `Jest` to fix `WS` vulnerability.
=> Bumping Jest to fix WS vulnerability

.github/workflows/ci.yaml, Makefile, examples/blueprint-construct/index.ts
Adds CDK validation steps to CI.
=> Updating sample construct

README.md
This pull request updates a decent amount of content in our Readme. 
=> Refreshing project readme

lib/addons/argocd/index.ts
=> Minor: removed too verbose output from argocd

lib/stacks/eks-blueprint-stack.ts, package.json
Addons did not finish executing when post deploy steps kicked in. 
=> fixed async behavior on addons and post deployment steps

lib/addons/cluster-autoscaler/index.ts, package.json
=> fixing CA failure on memory limits (customer reported)

docs/internal/readme-internal.md, examples/blueprint-construct/index.ts
=> fixing build, disabling reference data temporarily

ci/buildspec.yml
fixes ci failure introduced in #161 
=> add git user details so merge can succeed

mkdocs.yml
*Issue #, if available:* #180 
=> fix broken landing page link

README.md
=> update README.md for broken docs link

.eslintignore, lib/addons/appmesh/index.ts, lib/addons/argocd/index.ts, lib/addons/aws-loadbalancer-controller/index.ts, lib/addons/calico/index.ts, lib/addons/cluster-autoscaler/index.ts, lib/addons/external-dns/index.ts, lib/addons/index.ts, lib/addons/metrics-server/index.ts, lib/addons/nginx/index.ts, lib/addons/secrets-store/index.ts, lib/addons/ssm-agent/index.ts, lib/addons/xray/index.ts, lib/spi/types.ts, lib/utils/namespace-utils.ts
This pull request includes general cleanup of our add-on classes, including documenting props, classes and improving consistency across add-on implementations. 
=> Clean up for add-on interfaces

docs/addons/app-mesh.md, docs/addons/argo-cd.md, docs/addons/aws-load-balancer-controller.md, docs/addons/calico.md, docs/addons/cluster-autoscaler.md, docs/addons/container-insights.md, docs/addons/external-dns.md, docs/addons/metrics-server.md, docs/addons/nginx.md, docs/addons/secrets-store.md, docs/addons/ssm-agent.md, docs/addons/xray.md, docs/cluster-providers/ec2-cluster-provider.md, docs/getting-started.md
This pull request contains general cleanup for our add-on documentation. It fixes bugs and brings consistency to code samples. It also fixes typos in docs. 
=> Cleanup for add-on documentation

docs/advanced/multi-cluster-management.md, docs/cluster-providers/ec2-cluster-provider.md, docs/core-concepts.md, docs/getting-started.md, docs/index.md, docs/pipelines.md, docs/teams.md
=> Text revisions

README.md, docs/addons/calico.md, docs/getting-started.md, docs/index.md
=> Revised README; minor revisions to other .md files

README.md, docs/addons/app-mesh.md, docs/addons/argo-cd.md, docs/addons/aws-load-balancer-controller.md, docs/addons/calico.md, docs/addons/cluster-autoscaler.md, docs/addons/container-insights.md, docs/addons/external-dns.md, docs/addons/index.md, docs/addons/metrics-server.md, docs/addons/nginx.md, docs/addons/ssm-agent.md, docs/addons/xray.md, docs/advanced/multi-cluster-management.md, docs/cluster-providers/ec2-cluster-provider.md, docs/cluster-providers/index.md, docs/core-concepts.md, docs/getting-started.md, docs/pipelines.md, docs/teams.md, lib/addons/appmesh/index.ts, lib/addons/external-dns/index.ts, mkdocs.yml
=> Completed editing pass of all pages

docs/addons/velero.md
* Remove S3 VPC endpoint description from documentation. 
=> [Fix] Update docs for Velero

examples/teams/team-burnham/index.ts, lib/addons/secrets-store/secret-provider.ts
Added minor class under Secrets Provider; this will be leveraged under SSP Patterns.
=> added minor SecretsManager class

docs/cluster-providers/mng-cluster-provider.md
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
* Fixed a small typo in docs/cluster-providers/mng-cluster-provider.md
=> Fixed a typo in the MngClusterProvider docs

package.json
*Description of changes:* prepare to publish a new version with autoscaler and nginx add-on fixes.
=> version increment for release

docs/core-concepts.md, docs/extensibility.md, mkdocs.yml
This PR contains initial guide for extensibility. It also references the example add-on implementation https://github.com/shapirov103/ssp-eks-extension
=> Extensibility guide (add-ons)

lib/pipelines/code-pipeline.ts, package.json
=> fixed wave bug

lib/teams/index.ts
*Issue #, if available:* 293
*Description of changes:* Added namespace labels to the teams namespace  
=> Add namespace labels option to assist with the AWS App Mesh requirement

package.json
=> Update package.json to publish

docs/addons/index.md, lib/utils/secrets-manager-utils.ts
=> update docs and fixed error message log for secrets

.npmignore, ci/index.ts, docs/README.md, docs/addons/aws-node-termination-handler.md, docs/addons/ebs-csi-driver.md, docs/addons/kubecost.md, docs/addons/kubevious.md, docs/addons/secrets-store.md, docs/addons/velero.md, docs/cluster-management.md, docs/core-concepts.md, docs/extensibility.md, docs/pipelines.md, docs/resource-providers/index.md, tsconfig.json
*Description of changes:* fixed docs and other resources with correct references for CDK v2.
=> doc changes, left-over references

docs/addons/external-dns.md, docs/addons/nginx.md, docs/getting-started.md, docs/resource-providers/index.md, test/stacks.test.ts
*Description of changes:* external dns addon renaming (failures in tests fixed and documentation updates)
=> external dns addon renamed - test failures

docs/addons/index.md, docs/addons/newrelic.md
Adding documentation for the New Relic Addon.
=> Newrelic Addon documentation

docs/addons/datadog.md, docs/addons/index.md, mkdocs.yml
=> Datadog addon docs

docs/addons/kasten-k10.md
Kasten K10 Addon Documentation
=> Kasten K10 documentation

README.md, docs/index.md
Updates to readme and docs to align with TF messaging.
=> Updating docs and readme

docs/cluster-providers/generic-cluster-provider.md
N/A
Adding example for fargateProfiles on the Generic Cluster Provider documentation
=> Adding example for fargateProfiles on the Generic Cluster Provider documentation

docs/addons/keda.md, examples/blueprint-construct/index.ts, lib/addons/index.ts, lib/addons/keda/index.ts
=> Keda addon

docs/README.md, docs/index.md
The workshop for CDK EKS Blueprints is live - adding them to the docs (along with how to provide feedback leveraging issues page on this repository).
=> Adding workshop link

examples/blueprint-construct/index.ts, mkdocs.yml
Minor lint and doc update for 1.0.2 release
=> lint fixes and rafay navigation typo fix

docs/addons/karpenter.md, lib/addons/karpenter/index.ts, package.json
*Description of changes:* 
- Making updates to Karpenter docs in line with PR #421.
- Added ts-md5 package to a dependency to address #427. 
- Fixed incorrect type for taints to address #428.
=> Update Karpenter docs and bug fixes

lib/addons/karpenter/iam.ts
#463
Add `pricing:GetProducts` to policy
=> (fix) Fixing Karpenter IAM Policy for #463

examples/blueprint-construct/index.ts, lib/addons/falco/index.ts
=> removed falco from e2e for now. created issue to fix

docs/addons/external-secrets.md, docs/addons/index.md, examples/blueprint-construct/index.ts, lib/addons/external-secrets/index.ts, lib/addons/index.ts, mkdocs.yml
Adds [external-secrets](https://github.com/external-secrets/external-secrets) as an addon
=> feat: add external secrets addon

lib/addons/istio-base/index.ts
*Description of changes:* istio base release must complete before istio control plane is attempted release
=> Istio fails on dependency

README.md, ci/buildspec.yml, docs/README.md, docs/getting-started.md, examples/blueprint-construct/index.ts, lib/addons/appmesh/index.ts, lib/addons/calico-operator/index.ts, lib/addons/external-dns/index.ts, lib/addons/istio-base/index.ts, lib/addons/istio-control-plane/index.ts, lib/addons/karpenter/index.ts, lib/addons/keda/index.ts, lib/addons/kubevious/index.ts, lib/addons/nginx/index.ts, lib/addons/secrets-store/index.ts, lib/addons/velero/index.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/pipelines/code-pipeline.ts, package.json, test/clusterprovider.test.ts
Release 1.3.0 prep: upgraded helm charts, library versions
=> Release 1.3.0 prep: upgraded helm charts, library versions

package.json
=> version increment to 1.3.0

lib/addons/external-secrets/index.ts
fixes https://github.com/aws-quickstart/cdk-eks-blueprints/issues/509
=> fix(external-secrets): wait for eso deployed

docs/resource-providers/index.md, lib/cluster-providers/generic-cluster-provider.ts, lib/resource-providers/kms-key.ts, lib/spi/cluster-contracts.ts, lib/spi/types.ts, lib/stacks/eks-blueprint-stack.ts, test/resource-providers/kms-key.test.ts
fixes https://github.com/aws-quickstart/cdk-eks-blueprints/issues/482
=> feat(resource-provider): cluster secrets encryption key

examples/blueprint-construct/index.ts, lib/addons/karpenter/index.ts
#518 
Minor Karpenter addon change to allow setting ttlSecondsUntilExpired as requested per above issue.
=> Karpenter addon to allow setting ttlSecondsUntilExpired

lib/addons/cluster-autoscaler/index.ts, lib/cluster-providers/generic-cluster-provider.ts, package.json, test/clusterprovider.test.ts
=> Added lambda layers for 1.22 and 1.23

lib/addons/cluster-autoscaler/index.ts
*Fix for issue #531*
*Adding missing IAM policy. Check the issue #531 for more details *
=> Fix for issue #531

lib/teams/emr-on-eks-team.ts
Add the ability to add `tags` in EMR on EKS team props. These tags are applied to EMR on EKS virtual cluster.
=> Add EMR VC tag in props

README.md, docs/README.md, docs/getting-started.md, lib/addons/jupyterhub/index.ts, lib/pipelines/code-pipeline.ts, package.json
*Description of changes:*  fixing the CDK version issue for the Blueprints Workshop
=> fixing the CDK version issue for the Blueprints Workshop

README.md, docs/README.md, docs/getting-started.md, lib/pipelines/code-pipeline.ts
=> upgraded CDK to 2.51.1

lib/addons/jupyterhub/index.ts, test/jupyterhub.test.ts
*Issue #, if available:* None
*Description of changes:* Unit test added for jupyterhub
=> Minor JupyterHub fixes

CODEOWNERS
=> Added project admins to codeowners

docs/addons/index.md, docs/addons/xray.md, docs/getting-started.md, mkdocs.yml
*Issue #, if available:* 574
ACK addon added to navigation
Getting started guide examples updated
=> Getting started guide: failing examples

docs/addons/ebs-csi-driver.md, examples/blueprint-construct/index.ts, lib/addons/core-addon/index.ts, lib/addons/ebs-csi-driver/iam-policy.ts, lib/addons/ebs-csi-driver/index.ts
*1/Added IAM policy for the EBS CSI Driver to include a conditional KMS policy statement when KMS keys are passed. 2/Modified EBS CSI driver addon constructor to accept an optional kmsKeys array.*
=> Added KMS part of the IAM policy for the EBS CSI Driver optionally.

docs/getting-started.md
Add step to install `n` to manage node versions
=> Add step to install `n` to manage node versions

docs/addons/jupyterhub.md, examples/blueprint-construct/index.ts, lib/addons/jupyterhub/index.ts
Reverts aws-quickstart/cdk-eks-blueprints#606
=> Revert "Feature/Jupyterhub: Removed option to expose proxy svc using NLB"

docs/addons/ack-addon.md, lib/addons/ack/serviceMappings.ts
Updating ACK Chart versions and adding 5 new charts added to ACK.
=> Updating ACK Chart versions and Adding New ACK Charts

docs/addons/vpc-cni.md
=> Fixing Bug for Documentation for Pattern 3 VPC CNI

lib/addons/coredns/index.ts, lib/addons/ebs-csi-driver/index.ts, lib/addons/kube-proxy/index.ts, lib/addons/vpc-cni/index.ts
=> upgraded core addons for 1.25 support (1.24 as well)

lib/cluster-providers/generic-cluster-provider.ts, test/clusterprovider.test.ts
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/653
=> recreate InstanceType class when context is coming from cdk.json

examples/blueprint-construct/index.ts, lib/addons/aws-loadbalancer-controller/index.ts, lib/addons/cert-manager/index.ts, lib/addons/jupyterhub/index.ts, lib/utils/addon-utils.ts, test/emr-eks.test.ts
…anager and jupyter hub
Hidden dependency on AWS LB controller from jupyterhub and cert-manager addon cause sporadic issues.
=> solving dependendcy issue on AWS load balancer controller 

lib/addons/aws-loadbalancer-controller/index.ts, lib/utils/cluster-utils.ts
=> moved aws lb controller to deploy before capacity rollout

lib/addons/jupyterhub/index.ts
*Description of changes:* fixed this time. proper dependency handling for promise. 
=> fixed dependency issue of jupyterhub

lib/teams/team.ts
*Description of changes:* Adding support for a list of policies for application teams
=> Added ability to pass a list of policies to add to the IRSA account 

lib/teams/team.ts
=> fixed policy propagation to service account

lib/addons/cluster-autoscaler/index.ts
=> Fix issue #684

docs/addons/aws-node-termination-handler.md, docs/addons/jupyterhub.md, docs/addons/vpc-cni.md, docs/cluster-providers/generic-cluster-provider.md, docs/cluster-providers/mng-cluster-provider.md, docs/resource-providers/index.md, examples/blueprint-construct/index.ts, examples/examples.ts, lib/addons/cluster-autoscaler/index.ts, lib/addons/jupyterhub/index.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/resource-providers/utils.ts, lib/spi/resource-contracts.ts, lib/spi/types.ts, lib/stacks/eks-blueprint-stack.ts, package.json, test/clusterprovider.test.ts, test/constraints-validation.test.ts, test/resource-providers/resource-proxy.test.ts, test/stacks.test.ts
=> CFN resources can be returned by resource providers

lib/addons/apache-airflow/index.ts, lib/addons/index.ts
*Issue #, if available:* #651
*Description of changes:* Adding Apache Airflow as an add-on.
=> Apache Airflow Add-on

docs/addons/apache-airflow.md, examples/blueprint-construct/index.ts, lib/addons/apache-airflow/index.ts, lib/addons/index.ts
*Issue #, if available:* #651
- Refactoring code to include full custom helm values for S3, ALB and EFS implementations
- Commented out RDS implementation (as we await for RDS Provider PR to merge)
- Added documentations.
=> Apache Airflow update: Removed RDS for now, added doc and refactored codes

package.json
=> 1.9.0 release

docs/resource-providers/amp-provider.md, docs/resource-providers/certificate-providers.md, docs/resource-providers/efs-providers.md, docs/resource-providers/hosted-zone-providers.md, docs/resource-providers/iam-role-providers.md, docs/resource-providers/kms-key-providers.md, docs/resource-providers/s3-providers.md, docs/resource-providers/vpc-providers.md, mkdocs.yml
*Issue #, if available:* #688
*Description of changes:* Added documentation for all implemented resource providers.
=> Add more resource providers documentation

lib/addons/ack/serviceMappings.ts
=> Upgrading ACK Addon versions

docs/internal/ci.md
=> Release prep

lib/addons/cloudwatch-logs/index.ts
*Description of changes:* cloudwatch addon (fluentbit chart) upgraded to the latest version. 
=> upgraded version from the cloud watch addon backed by fluentbit

.npmignore, package.json
*Description of changes:* reduced size from 9 MB to 415 KB, added metadata
=> reduced packaged size, added metadata to the package.json

mkdocs.yml
=> Added missing nav link for Instana

docs/internal/input-validations-framework-readme.md, lib/addons/argocd/index.ts, lib/spi/types.ts, lib/utils/constraints-utils.ts, test/constraints-validation.test.ts
*Issue #, if available:* #752
Added new constraints to ensure argocd credentials secret name will be correct regex.  Also added composite constraint and general regex constraint.
=> Argocd check

lib/addons/core-addon/index.ts
Moved debug statement to only show after auto selection
=> move debug statement to make more sense

lib/addons/fluxcd/index.ts, lib/addons/fluxcd/kustomization.ts
=> Added support for multi path in fluxcd addon

docs/addons/karpenter.md
*Issue #, if available:* #764
*Description of changes:* Updating the Karpenter Addon Doc to ensure it works properly.
=> (Karpenter addon) Doc Fix

docs/addons/amp-addon.md, lib/addons/amp/index.ts, test/amp.test.ts, test/resources/recording-rules-test.yml
=> Configurations of OpenTelemetryCollector and AMP Rules for AmpAddOn

.github/workflows/docbuild.yml
=> Fixing GH Action issues

docs/addons/fluxcd.md, lib/addons/fluxcd/gitrepository.ts, lib/addons/fluxcd/index.ts, lib/addons/fluxcd/kustomization.ts
this needs to be reviewed tested and approved by zjaco13 to check compatibility with his original use case and avoid further conflicts between the 2 PRs
see related bug report for details
=> FluxCD fails to deploy multiple Kustomizations following PR #794

Makefile, docs/READMEv2.md, lib/codegen/addons.ts, lib/codegen/cluster.ts, lib/codegen/cluster_providers.ts, lib/codegen/resource_providers.ts, lib/codegen/teams.ts, lib/server/index.ts, proto/addons.proto, proto/cluster.proto
=> Add more object rpcs

.github/workflows/linkcheck.json, docs/addons/coredns.md, lib/addons/coredns/index.ts, lib/addons/fluxcd/index.ts
Modified coredns addon to include more props than just the version
=> Coredns props extended

.github/workflows/linkcheck.json, docs/builders/windows-builder.md, lib/builders/windows-builder.ts, mkdocs.yml
Windows Builder for Windows Blueprints
=> Windows Builder for Windows Blueprints

docs/resource-providers/vpc-providers.md
=> fixed documentation for direct VPC provider

examples/blueprint-construct/index.ts, lib/builders/observability-builder.ts, package.json
=> Fix for ObservabilityBuilder

package.json
Update Zod due to vulnerability  
https://github.com/advisories/GHSA-m95q-7qp3-xv42
=> Update zod package due to vulnerability

docs/builders/graviton-builder.md
Fix title on the Graviton Builder documentation page.
=> docs: Fix title on the Graviton Builder documentation page

lib/addons/cloudwatch-logs/iam-policy.ts, lib/addons/cloudwatch-logs/index.ts
=> CloudWatchLogsAddon: setting logRetentionDays param does not work and not set cloudWatchLogs.logRetentionDays when creating CloudWatch Log Groups

lib/builders/observability-builder.ts, package.json
=> Upgrade cloudWatchInsightsAddOn in Observability Builder

docs/addons/index.md, mkdocs.yml
Added Neuron addon to docs/addons/index.md and  mkdocs.yml as requested in the comments of this PR:  https://github.com/aws-quickstart/cdk-eks-blueprints/pull/777
=> Neuron Device Plugin Addon Continuation

lib/cluster-providers/import-cluster-provider.ts, lib/utils/id-utils.ts, test/clusterprovider.test.ts
*Issue #, if available:* #916
Import cluster provider can handle cluster name as token. 
=> Fixes #916

lib/addons/adot/index.ts, lib/addons/core-addon/index.ts
*Issue #, if available:* #930
Refactored core addon and adot addon to handle proper namespace dependencies. 
=> Bugfix: ADOT fails intermittently 

lib/addons/adot/index.ts, lib/addons/cloud-watch-insights/index.ts, lib/addons/coredns/index.ts, lib/addons/ebs-csi-driver/index.ts, lib/addons/eks-pod-identity-agent/index.ts, lib/addons/kube-proxy/index.ts, lib/addons/vpc-cni/index.ts
=> amended versions

lib/addons/cluster-autoscaler/index.ts
*Issue #, if available: #957
*Description of changes:
- Add dependency between ServiceAccount and Namespace Creation
=> ClusterAutoScalerAddOn: Bug Fix on Namespace dependency #957

examples/blueprint-construct/index.ts, lib/addons/ebs-csi-driver/index.ts
Fix EBS CSI Driver Issue - Avoiding `CoreAddonProps` to be filled out 
=> Fix EBS CSI Driver Issue - Avoiding `CoreAddonProps` to be filled out 

lib/addons/cloud-watch-insights/iam-policy.ts, lib/addons/cloud-watch-insights/index.ts, test/cloudwatch-insights.test.ts
Added test cases to ensure all information is being passed downstream.
*Issue #, if available:* #948
=> Fix CloudWatch Insights Addon - User passed version not being respected

lib/addons/ebs-csi-driver/index.ts
=> Moved version into explicit Props for EBS CSI

lib/addons/adot/index.ts, test/adot.test.ts
*Issue #, if available:* #972 
Update to omit (or make optional) **version** from AdotCollectorAddOnProps
=> Omit version to AdotCollectorAddOnProps

docs/cluster-providers/mng-cluster-provider.md
=> Remove the second 'version' declaration

lib/addons/vpc-cni/index.ts
=> Fixing Issue #1011

docs/README.md, docs/cluster-management.md, docs/cluster-providers/mng-cluster-provider.md, docs/getting-started.md, docs/pipelines.md
=> documentation updates for 1.15

lib/addons/cloud-watch-insights/index.ts, lib/addons/karpenter/index.ts, test/cloudwatch-insights.test.ts
=> Upgraded CloudWatchInsight to v1.7 and fixed unit tests

.devcontainer/devcontainer.json, README.md, docs/README.md, docs/getting-started.md, docs/internal/ci.md, lib/addons/argocd/index.ts, lib/addons/efs-csi-driver/index.ts, lib/addons/ingress-nginx/index.ts, lib/addons/kube-state-metrics/index.ts, lib/addons/prometheus-node-exporter/index.ts, lib/pipelines/code-pipeline.ts, package.json
=> 1.15.1 Patch Release

lib/addons/cloud-watch-insights/index.ts
=> Incremented cloudwatch insight versions to address the test failures

README.md
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/1056
The readme mentions this ingress, but isn't currently deploying it. This PR fixes that
=> [fix] Add documented nginx

.github/workflows/markdown-link-check.yaml, README.md
=> Fixing GH Action Error

bin/main.ts, examples/blueprint-construct/index.ts, lib/addons/adot/index.ts, lib/addons/apache-airflow/index.ts, lib/addons/cloud-watch-insights/index.ts, lib/addons/karpenter/index.ts, lib/addons/velero/index.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/stacks/eks-blueprint-construct.ts, lib/utils/log-utils.ts, lib/utils/namespace-utils.ts, package.json
=> Added support for 1.31 and default EKS/k8s version is set to 1.30

.github/workflows/ci.yaml
=> Fixing cache version in the actions

docs/addons/adot-addon.md, lib/addons/adot/index.ts, lib/addons/gpu-operator/index.ts
Adding ADOT Collector Version Support for EKS V1.31
=> Adding ADOT Collector Version Support for EKS V1.31

examples/examples.ts, lib/cluster-providers/generic-cluster-provider.ts, lib/stacks/eks-blueprint-construct.ts, lib/utils/context-utils.ts
*Issue #, if available:* #1147
=> Private cluster ignores explicit boolean attribute passed to the cluster provider (regression)

examples/blueprint-construct/index.ts, lib/addons/karpenter/types.ts, package.json
*Issue #, if available:* #1148
=>  Invalid value in the consolidation policy for v1 karpenter

mkdocs.yml
Adds automode builder documentation to docs nav bar
=> fix: Update mkdocs.yml to add automode builder to nav

lib/addons/index.ts, lib/addons/usage-tracking/index.ts, lib/builders/automode-builder.ts, lib/builders/bedrock-builder.ts, lib/builders/gpu-builder.ts, lib/builders/graviton-builder.ts, lib/builders/observability-builder.ts, lib/builders/windows-builder.ts, test/usage-tracking.test.ts
Use tags to track different builder usage
=> Use tags to track different builder usage

lib/addons/ebs-csi-driver/iam-policy.ts
*Issue #, if available:* #1151
=> Added iam policy to support snapshotting for EBS CSI driver

lib/addons/karpenter/types.ts
*Issue #, if available:* #1161
*Description of changes:* AL2023 added to karpenter ECNodeClass as an option
=> AL2023 added to karpenter ECNodeClass as an option

lib/addons/aws-loadbalancer-controller/index.ts, lib/addons/core-addon/index.ts, lib/addons/coredns/index.ts, lib/addons/helm-addon/index.ts, lib/addons/karpenter/karpenter-v1.ts, lib/addons/kube-proxy/index.ts, lib/cluster-providers/generic-cluster-provider-v2.ts, lib/spi/addon-contracts.ts, lib/utils/addon-utils.ts, lib/utils/cluster-utils.ts
#1168
fixes error when version is null or auto
=> fix version error for automode addons

lib/addons/ack/serviceMappings.ts
=> Update ack charts version and add new options
